// <auto-generated />
using System;
using DHLWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DHLWebAPI.Migrations
{
    [DbContext(typeof(DHLContext))]
    partial class DHLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.3.20181.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DHLWebAPI.Models.TblAddress", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLabel")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdAddressType")
                        .HasColumnType("int");

                    b.Property<string>("LunchTimeEnd")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("LunchTimeStart")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("OpenTimeEnd")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("OpenTimeStart")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("PostAddress")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("PostAddressNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("PostIntern")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("IdAddress");

                    b.HasIndex("IdAddressType");

                    b.ToTable("tbl_address");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblAddressType", b =>
                {
                    b.Property<int>("IdAddressType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdressType")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdAddressType");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_address_type");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCardStatus", b =>
                {
                    b.Property<int>("IdCardStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardStatus")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdCardStatus");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_card_status");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCards", b =>
                {
                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<float>("BalanceAvailable")
                        .HasColumnType("real");

                    b.Property<int>("CardStatus")
                        .HasColumnType("int");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdCustomer")
                        .HasName("PK__tbl_card__DB43864A309309D5");

                    b.HasIndex("CardStatus");

                    b.HasIndex("IdCard")
                        .IsUnique()
                        .HasName("UQ__tbl_card__3B7B33C30302E6B9");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_cards");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerAddress", b =>
                {
                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdAddress")
                        .HasColumnType("int");

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdCustomer", "IdAddress")
                        .HasName("PK__tbl_cust__345F797D18461953");

                    b.HasIndex("IdAddress");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_customer_address");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerDiscount", b =>
                {
                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdDiscount")
                        .HasColumnType("int");

                    b.Property<string>("CodeForActive")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IdCustomer", "IdDiscount")
                        .HasName("PK__tbl_cust__E72988E9763FF381");

                    b.HasIndex("IdDiscount");

                    b.HasIndex("InsertBy");

                    b.ToTable("tbl_customer_discount");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerLogs", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PID")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerXml")
                        .IsRequired()
                        .HasColumnName("CustomerXML")
                        .HasColumnType("xml");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdTool")
                        .HasColumnType("int")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.HasKey("Pid");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdTool");

                    b.HasIndex("InsertBy");

                    b.ToTable("tbl_customer_logs");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerStatus", b =>
                {
                    b.Property<int>("IdCustomerStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdCustomerStatus");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_customer_status");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerType", b =>
                {
                    b.Property<int>("IdCustomerType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdCustomerType");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_customer_type");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomers", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<int>("CustomerStatus")
                        .HasColumnType("int");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("FiscalCode")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<int?>("IdDiscount")
                        .HasColumnType("int");

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Iva")
                        .HasColumnName("IVA")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Pec")
                        .HasColumnName("PEC")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Sdi")
                        .HasColumnName("SDI")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdCustomer");

                    b.HasIndex("CustomerStatus");

                    b.HasIndex("CustomerType");

                    b.HasIndex("IdDiscount");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_customers");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblDiscountType", b =>
                {
                    b.Property<int>("IdDiscountType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("DiscountTypeTitle")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdDiscountType");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_discount_type");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblDiscounts", b =>
                {
                    b.Property<int>("IdDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiscountDescription")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<DateTime>("DiscountEndDate")
                        .HasColumnType("date");

                    b.Property<float>("DiscountPerc")
                        .HasColumnType("real");

                    b.Property<DateTime>("DiscountStartDate")
                        .HasColumnType("date");

                    b.Property<string>("DiscountTitle")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<bool>("DiscountToActive")
                        .HasColumnType("bit");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("IdDiscount");

                    b.HasIndex("DiscountType");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_discounts");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblProductDiscount", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdDiscount")
                        .HasColumnType("int");

                    b.Property<string>("CodeForActive")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IdProduct", "IdDiscount")
                        .HasName("PK__tbl_prod__12E34877E8452339");

                    b.HasIndex("IdDiscount");

                    b.HasIndex("InsertBy");

                    b.ToTable("tbl_product_discount");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblProducts", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertData")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdProduct");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_products");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblProfilePermission", b =>
                {
                    b.Property<string>("ProfileSetName")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("ProfileSetName")
                        .HasName("PK__tbl_prof__ABF29A35D7291A0D");

                    b.HasIndex("IdProfile");

                    b.ToTable("tbl_profile_permission");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblShipments", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PID")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Awb")
                        .HasColumnName("AWB")
                        .HasColumnType("bigint");

                    b.Property<bool>("CheckPointFound")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatetimeCreation")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCostumer")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdTool")
                        .HasColumnType("int")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool>("ImmediateInvoicing")
                        .HasColumnType("bit");

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime");

                    b.Property<float>("TotalInvoice")
                        .HasColumnType("real");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Pid");

                    b.HasIndex("IdCostumer");

                    b.HasIndex("IdTool");

                    b.HasIndex("InsertBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("tbl_shipments");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblToolPermission", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("IdProfile")
                        .HasName("PK__tbl_tool__120435C18A2526A2");

                    b.ToTable("tbl_tool_permission");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblTools", b =>
                {
                    b.Property<int>("IdTool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<byte[]>("ToolKey")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .IsFixedLength(true)
                        .HasMaxLength(32);

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool>("ToolStatus")
                        .HasColumnType("bit");

                    b.HasKey("IdTool");

                    b.HasIndex("IdProfile");

                    b.ToTable("tbl_tools");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblTransactionLogs", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PID")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Awb")
                        .HasColumnName("AWB")
                        .HasColumnType("bigint");

                    b.Property<bool>("Awbstatus")
                        .HasColumnName("AWBStatus")
                        .HasColumnType("bit");

                    b.Property<string>("IdCard")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdTool")
                        .HasColumnType("int")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnName("TransactionID")
                        .HasColumnType("varchar(18)")
                        .HasMaxLength(18)
                        .IsUnicode(false);

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Pid");

                    b.HasIndex("IdCard");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdTool");

                    b.HasIndex("InsertBy");

                    b.ToTable("tbl_transaction_logs");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblUserType", b =>
                {
                    b.Property<int>("IdUserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("InsertBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserTypeTitle")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdUserType");

                    b.ToTable("tbl_user_type");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblUsers", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("Hiredate")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TitleOfCourtesy")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdUser");

                    b.HasIndex("UserType");

                    b.ToTable("tbl_users");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblAddress", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblAddressType", "IdAddressTypeNavigation")
                        .WithMany("TblAddress")
                        .HasForeignKey("IdAddressType")
                        .HasConstraintName("FK__tbl_addre__IdAdd__4F7CD00D")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblAddressType", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblAddressTypeInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_addre__Inser__5070F446")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblAddressTypeUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_addre__Updat__5165187F");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCardStatus", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblCardStatus")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_card___Updat__52593CB8")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCards", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblCardStatus", "CardStatusNavigation")
                        .WithMany("TblCards")
                        .HasForeignKey("CardStatus")
                        .HasConstraintName("FK__tbl_cards__CardS__534D60F1")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblCustomers", "IdCustomerNavigation")
                        .WithOne("TblCards")
                        .HasForeignKey("DHLWebAPI.Models.TblCards", "IdCustomer")
                        .HasConstraintName("FK__tbl_cards__IdCus__5441852A")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCardsInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_cards__Inser__5535A963")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblCardsUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_cards__Updat__5629CD9C")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerAddress", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblAddress", "IdAddressNavigation")
                        .WithMany("TblCustomerAddress")
                        .HasForeignKey("IdAddress")
                        .HasConstraintName("FK__tbl_custo__IdAdd__571DF1D5")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblCustomers", "IdCustomerNavigation")
                        .WithMany("TblCustomerAddress")
                        .HasForeignKey("IdCustomer")
                        .HasConstraintName("FK__tbl_custo__IdCus__5812160E")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCustomerAddressInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_custo__Inser__59063A47")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblCustomerAddressUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_custo__Updat__59FA5E80")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerDiscount", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblCustomers", "IdCustomerNavigation")
                        .WithMany("TblCustomerDiscount")
                        .HasForeignKey("IdCustomer")
                        .HasConstraintName("FK__tbl_custo__IdCus__5AEE82B9")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblDiscounts", "IdDiscountNavigation")
                        .WithMany("TblCustomerDiscount")
                        .HasForeignKey("IdDiscount")
                        .HasConstraintName("FK__tbl_custo__IdDis__5BE2A6F2")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCustomerDiscount")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_custo__Inser__5CD6CB2B")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerLogs", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblCustomers", "IdCustomerNavigation")
                        .WithMany("TblCustomerLogs")
                        .HasForeignKey("IdCustomer")
                        .HasConstraintName("FK__tbl_custo__IdCus__5DCAEF64")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblTools", "IdToolNavigation")
                        .WithMany("TblCustomerLogs")
                        .HasForeignKey("IdTool")
                        .HasConstraintName("FK__tbl_custo__IdToo__5EBF139D")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCustomerLogs")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_custo__Inser__5FB337D6")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerStatus", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCustomerStatusInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_custo__Inser__60A75C0F")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblCustomerStatusUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_custo__Updat__619B8048")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomerType", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCustomerTypeInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_custo__Inser__628FA481")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblCustomerTypeUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_custo__Updat__6383C8BA")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblCustomers", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblCustomerStatus", "CustomerStatusNavigation")
                        .WithMany("TblCustomers")
                        .HasForeignKey("CustomerStatus")
                        .HasConstraintName("FK__tbl_custo__Custo__656C112C")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblCustomerType", "CustomerTypeNavigation")
                        .WithMany("TblCustomers")
                        .HasForeignKey("CustomerType")
                        .HasConstraintName("FK__tbl_custo__Custo__6477ECF3")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblDiscounts", "IdDiscountNavigation")
                        .WithMany("TblCustomers")
                        .HasForeignKey("IdDiscount")
                        .HasConstraintName("FK__tbl_custo__IdDis__66603565");

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblCustomersInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_custo__Inser__6754599E")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblCustomersUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_custo__Updat__68487DD7")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblDiscountType", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblDiscountTypeInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_disco__Inser__6C190EBB")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblDiscountTypeUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_disco__Updat__6D0D32F4")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblDiscounts", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblDiscountType", "DiscountTypeNavigation")
                        .WithMany("TblDiscounts")
                        .HasForeignKey("DiscountType")
                        .HasConstraintName("FK__tbl_disco__Disco__6E01572D")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblDiscountsInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_disco__Inser__6EF57B66")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblDiscountsUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_disco__Updat__6FE99F9F")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblProductDiscount", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblDiscounts", "IdDiscountNavigation")
                        .WithMany("TblProductDiscount")
                        .HasForeignKey("IdDiscount")
                        .HasConstraintName("FK__tbl_produ__IdDis__70DDC3D8")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblProducts", "IdProductNavigation")
                        .WithMany("TblProductDiscount")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK_tbl_product_discount_tbl_products")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblProductDiscount")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_produ__Inser__71D1E811");
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblProducts", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblProductsInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_produ__Inser__73BA3083")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdatedByNavigation")
                        .WithMany("TblProductsUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__tbl_produ__Updat__74AE54BC")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblProfilePermission", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblToolPermission", "IdProfileNavigation")
                        .WithMany("TblProfilePermission")
                        .HasForeignKey("IdProfile")
                        .HasConstraintName("FK__tbl_profi__IdPro__75A278F5")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblShipments", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblCustomers", "IdCostumerNavigation")
                        .WithMany("TblShipments")
                        .HasForeignKey("IdCostumer")
                        .HasConstraintName("FK__tbl_shipm__IdCos__76969D2E")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblTools", "IdToolNavigation")
                        .WithMany("TblShipments")
                        .HasForeignKey("IdTool")
                        .HasConstraintName("FK__tbl_shipm__IdToo__778AC167")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblShipmentsInsertByNavigation")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_shipm__Inser__787EE5A0")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "UpdateByNavigation")
                        .WithMany("TblShipmentsUpdateByNavigation")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK__tbl_shipm__Updat__797309D9")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblTools", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblToolPermission", "IdProfileNavigation")
                        .WithMany("TblTools")
                        .HasForeignKey("IdProfile")
                        .HasConstraintName("FK__tbl_tools__IdPro__7A672E12")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblTransactionLogs", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblCards", "IdCardNavigation")
                        .WithMany("TblTransactionLogs")
                        .HasForeignKey("IdCard")
                        .HasConstraintName("FK__tbl_trans__IdCar__7B5B524B")
                        .HasPrincipalKey("IdCard");

                    b.HasOne("DHLWebAPI.Models.TblCustomers", "IdCustomerNavigation")
                        .WithMany("TblTransactionLogs")
                        .HasForeignKey("IdCustomer")
                        .HasConstraintName("FK__tbl_trans__IdCus__7C4F7684")
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblTools", "IdToolNavigation")
                        .WithMany("TblTransactionLogs")
                        .HasForeignKey("IdTool")
                        .HasConstraintName("FK__tbl_trans__IdToo__7D439ABD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DHLWebAPI.Models.TblUsers", "InsertByNavigation")
                        .WithMany("TblTransactionLogs")
                        .HasForeignKey("InsertBy")
                        .HasConstraintName("FK__tbl_trans__Inser__7E37BEF6")
                        .IsRequired();
                });

            modelBuilder.Entity("DHLWebAPI.Models.TblUsers", b =>
                {
                    b.HasOne("DHLWebAPI.Models.TblUserType", "UserTypeNavigation")
                        .WithMany("TblUsers")
                        .HasForeignKey("UserType")
                        .HasConstraintName("FK__tbl_users__UserT__7F2BE32F")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
